[package]
name = "bindings"
version = "0.1.0"
authors = ["ElGusanitoPLAY <nyagouno@gmail.com>"]
edition = "2018"

[target.'cfg(windows)'.dependencies]
windows = "0.9.1"

[target.'cfg(windows)'.build-dependencies]
windows = "0.9.1"
